Repository CA-G12/CUMaps, pull requests merged in 2022-08, with the labels that each got.

#6 create file strcure relates #1
  index.html
  js/dom.js
  js/fetch.js
  js/logic.js
  style.css
  test/test.test.js
  uneversty/index.html
Labels: done

#8 create fetch function that take tow parameter api url and callbake f…
  index.html
  js/fetch.js
Labels: awaiting-review

#9 Header page
  img/home-img.avif
  index.html
  js/dom.js
  js/logic.js
  style.css
Labels: done

#10 create card in dom without style relates #3
  index.html
  js/dom.js
  js/fetch.js
  js/logic.js
  style.css
Labels: done

#11 3 create main landing page
  .vscode/settings.json
  index.html
  js/dom.js
  js/fetch.js
  style.css
Labels: awaiting-review, in-progress

#13 create univetsty page header and main section relates #12
  js/dom.js
  uneversty/index.html
Labels: done

#15 adding main for university page using dom and get data
  js/dom.js
  js/fetch.js
  style.css
  university/index.html
Labels: done

#16 add search logic for country page and universty page relates #14
  index.html
  js/dom.js
  js/logic.js
  university/index.html
Labels: done

#17 adding footer page for landing page and university page
  index.html
  style.css
  university/index.html
Labels: done

#19 adding responsive design in page
  index.html
  js/logic.js
  style.css
  university/index.html
Labels: done

#21 adding readme file for my web
  README.md
Labels: done

#24 change call page
  js/dom.js
Labels: done, in-progress
